# Generated by Django 3.2.9 on 2021-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211228_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='author',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='movies',
            name='year_published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
