# Generated by Django 3.2.9 on 2021-12-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211228_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.TextField(default='Author name..')),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(default='Title of the book')),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
